### ISSUE TITLE
Unable to set token

### ISSUE THREAD

**Issue by s8sachin** [kevva/imgur-uploader#3]
I tried without passing token, image was uploaded successfull, 
then i tried passing token in options like this.
```  
imgurUploader('https://avatars1.githubusercontent.com/u/709159?s=400&v=4', {title: 'Hello!', token: '34b90e75ab1c04b'})
```
but i am getting error :
```
{ HTTPError: Response code 403 (Forbidden)
    at stream.catch.then.data (/home/qwinix/Documents/Private-Dir/meme_review/node_modules/got/index.js:182:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'HTTPError',
  host: 'api.imgur.com',
  hostname: 'api.imgur.com',
  method: 'POST',
  path: '/3/image',
  protocol: 'https:',
  url: 'https://api.imgur.com/3/image',
  statusCode: 403,
  statusMessage: 'Forbidden',
  headers: 
   { 'access-control-allow-headers': 'Authorization, Content-Type, Accept, X-Mashape-Authorization, IMGURPLATFORM, IMGURUIDJAFO, SESSIONCOUNT, IMGURMWBETA, IMGURMWBETAOPTIN',
     'access-control-allow-methods': 'GET, PUT, POST, DELETE, OPTIONS',
     'access-control-allow-origin': '*',
     'access-control-expose-headers': 'X-RateLimit-ClientLimit, X-RateLimit-ClientRemaining, X-RateLimit-UserLimit, X-RateLimit-UserRemaining, X-RateLimit-UserReset',
     'cache-control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0',
     'content-encoding': 'gzip',
     'content-type': 'application/json',
     date: 'Sun, 13 May 2018 08:07:47 GMT',
     etag: 'W/"92568deb19743a1a30078a1c4fb8785080db97f7"',
     server: 'nginx',
     vary: 'Accept-Encoding',
     'x-post-rate-limit-limit': '1250',
     'x-post-rate-limit-remaining': '1235',
     'x-post-rate-limit-reset': '906',
     'content-length': '117',
     connection: 'Close' } }
```

**Comment by AdamHordines** [comment]
I don't know if you still need help with this, but I had the same issue. Solved by adding `Client-ID` in front of the token: `... {title: 'Hello!', token: 'Client-ID 34b90e75ab1c04b'} ...`
